### ISSUE TITLE
Re-discuss the workflow

### ISSUE THREAD

**Issue by doudou** [rock-core/vscode-rock#14]
I generally don't like doing things differently than the platform we're running on. VSCode has UI paths to build and debug, we should use them and not create parallel ones. The build and debug buttons in the status bar look like a case of "I like my way better than the VS people's way" IMO.

**Comment by g-arjones** [comment]
What do you suggest? The whole point of the extension IMO is to save the user from writing launch.json and tasks.json (specially for ruby and orogen packages, which requires both files). This simply isn't an acceptable workflow in a component-based framework like rock.

**Comment by doudou** [comment]
I'll investigate, but I'm assuming that one can provide a configuration without the user's interaction, that can then be edited by him if he/she wants it. It looks like this at least from my playing around.

**Comment by g-arjones** [comment]
I don't think that is possible.. Also, don't think we can use preLaunchTasks provided by the extension in that way. But I didn't dig deep so I may be wrong here

**Comment by doudou** [comment]
From what I played with today, I think the following might be doable (this in effect is my proposal):

- use build tasks for build and update (move the update/... back to Build tasks because build tasks are the only thing that are easy to access. non-build tasks are not directly accessible). Add "... Current Package" tasks that are resolved dynamically to use the auto/manual package selection mechanism.
- I would personally prefer removing the button from the status bar (since the VS guys didn't add one, and since it would be confusing to have the build button not build the default build task but only what Rock considers the default build task). But I won't fight over this.
- have a command to generate launch entries for a binary (C++), ruby script (Ruby) or orogen component name and task name (orogen). The launch configuration is accessible from the WorkspaceConfiguration object - so no need to edit the json file "by hand". The workflow is then: create debug entry (from palette/menu) and then run it and/or edit it from launch.json.
- maybe define snippets to add those entries from within the launch.json editor directly
- investigate whether we can do autocompletion of entries within launch.json

- [C++] use the debug configuration provider mechanism to allow the 'command' field to be relative to the build directory (or even to the bin/ and test/ folders). E.g. 'suite' becomes `/path/to/build/dir/test/suite`
- [orogen] use the debug configuration provider mechanism to allow the 'command' field to be an orogen model and task name, which are then translated into the relevant entries. E.g. `iodrivers_base::Proxy/task` becomes `prelaunch rock-run iodrivers_base::Proxy and attach gdb`
- [orogen] it is possible to have a preLaunchTask from within launch.json. What is unclear to me is whether we can get the task context from there, or if we will have to generate the prelaunchtask within resolveDebugConfiguration
- [all] add the relevant `autoproj exec` stanzas when possible, when not possible have a script within the package that provides the relevant interface.

**Comment by g-arjones** [comment]
> move the update/... back to Build tasks because build tasks are the only thing that are easy to access. non-build tasks are not directly accessible

What do you mean they are not directly accessible? Build tasks are accessible through the "Run Build Task" menu and non-build through "Run Task". As I user, I don't expect update/checkout to show up as build tasks and I don't see how that improves the experience.

> I would personally prefer removing the button from the status bar

I am ok with that. In this case, the whole "selected package" thing is useless and should be removed as well. 

The debugging stuff is what I have problems with. Unless we figure out how to create the launch.json file automatically and update it automatically (to switch targets) I would rather keep an alternative launching mechanism that is convenient and works without any setting up. I really don't want to make editing launch.json a part of my workflow every time I want to switch debugging targets. The situation is even worse with orogen packages since we can't use preLaunchTasks provided by a registered task provider, so changing the target would mean editing both tasks.json and launch.json (or running the pre launch task from the resolve methods of the debug configuration provider, which is very hacky IMO).

We can (and should) still use the debugging configuration provider to integrate with vscode's launching mechanism. But this mechanism is not convenient enough so I would prefer to keep that as an alternative.

> [all] add the relevant autoproj exec stanzas when possible, when not possible have a script within the package that provides the relevant interface.

I don't understand how this would work. For example, we can't tell the the Ruby debugger to run a script instead of "rdebug-ide" and the debugger can't follow exec(), so... Could you elaborate?

**Comment by g-arjones** [comment]
So, I spent some time thinking how we could come to a middle ground between my preferences (not having to edit json files as part of the workflow) and yours (seamless integration with vscode launching/task mechanisms). What I think that could work for both of us is an implementation that would:

1. Ensure that tasks.json and launch.json exists at all times for every open folder (maybe even with a file watcher);
2. Manage a "default"/"reserved" task (to be used as a preLaunchTask) and launch entry. The extension has to guarantee that these entries are always present;
3. Even though the user would still be able to edit the "default" entries if he/she wishes, some fields would be managed by the extension through the UI (like orogen launching options and debugging target);
4. Ideally, the extension would warn the user if he/she creates more than one "default" task and/or launcher for a package (I believe this is possible using json schemas).

If we could get this to work reliably, we could ditch the whole "package selection" thing completely, and since we agreed to not allow unregistered packages, the package type picker could be removed as well. The codebase would be greatly reduced and simplified.

Commands that target a specific package (debug target picking, envsh, etc) could bring up a picker ui so the user could choose which package the command will be applied to. Or we could keep the package selection mechanism for these cases, I am fine with either.

What do you think?

**Comment by doudou** [comment]
> What do you mean by "they are not directly accessible"? Build tasks are accessible through the "Run Build Task" menu and non-build through "Run Task". As a user, I don't expect update/checkout to show up as build tasks and I don't see how that improves the experience.

Build tasks are assigned by default to Shift+Ctrl+B and the last run build task is under F9. The only way you can access run tasks is through the menu or the palette. I won't fight over this. I have the feeling I would prefer the other option, but I'm OK with sticking with the current setup for now, and see how it goes.

> [debugging mechanisms]

I don't get the problem you're having. You don't have to switch targets within a launch file, you create a launch configuration per target. To avoid having to edit the launch configuration manually, my idea was to provide the user with a specific command (or some other mechanism) to add one new configuration to the existing ones, with a known binary (orogen model, ruby script, ...). This configuration can then be edited to tune it

Among the things we get with this are:
- the ability to *switch* launch configurations. With the current mechanism, I have to pick a binary and arguments each time I want to run something else than the current target. It will get very tiring very quickly. Launch configurations by contrast can easily be switched.
- we don't have to have launch-related code apart from the generator.
- the ability to *share* launch configurations. By having the debug provider resolve binaries w.r.t. the build directory, we allow people to have a configuration that is independent from the local workspace configuration.
- the ability to add arguments (for C++ and Ruby packages). Maybe select a configuration for oroGen package.

> EDIT: Actually, I think the type picker has to stay (for packages that are not in any package set)..

Not necessarily. Autoproj's auto-add mechanism infers the package type (it has to in order to build).

**Comment by g-arjones** [comment]
> but I'm OK with sticking with the current setup for now

Let's please do that, if it starts to get too inconvenient we re-discuss adding every task as build tasks again.

> I don't get the problem you're having

OK, _now_ I think I get what you are suggesting. This is good enough for me.

> the ability to switch launch configurations. 

This is particularly good! 👍 

> Not necessarily. Autoproj's auto-add mechanism infers the package type (it has to in order to build).

Fair enough, no need for type pickers then...
